# Generated by Django 5.1.5 on 2025-01-18 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postinteraction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='author_did',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='liked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='post_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'post_cid'), name='unique_user_post'),
        ),
    ]
