# Generated by Django 5.1.5 on 2025-01-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0002_alter_postinteraction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinteraction',
            name='double_dislike',
            field=models.BooleanField(default=False),
        ),
    ]
